### ISSUE TITLE
Set Disabled Device as A default device

### ISSUE THREAD

**Issue by EbramTawfik** [Belphemur/AudioDefaultSwitcher#1]
I am using:
                     `AudioController.SwitchTo(DeviceID, DeviceRole.All);`

Is There a way to enable the audio device if it's disabled and then set it as a default device?
Like this 
![image](https://user-images.githubusercontent.com/12788360/47314295-26893f00-d5f6-11e8-803e-ffa14294436b.png)

**Comment by Belphemur** [comment]
Hello, 

This is outside of the scope of the library.
It seems that Windows doesn't provide an API for it either, I couldn't find any documentation on this specific API.

All I found is this:
https://stackoverflow.com/questions/16931228/enabling-and-disabling-playback-and-recording-devices

**Comment by EbramTawfik** [comment]
Do you think Activate the device will fix it?
https://docs.microsoft.com/en-us/windows/desktop/api/mmdeviceapi/nf-mmdeviceapi-immdevice-activate
